// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uulmsmyubkdzvyzswtje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1bG1zbXl1YmtkenZ5enN3dGplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExODUxNDEsImV4cCI6MjA1Njc2MTE0MX0._r7p0OEfFPzAxKO6jC_5WVJbQflchL6svM38A9HL_Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);